### ISSUE TITLE
Support restarting Nomad without restarting nspawn containers

### ISSUE THREAD

**Issue by mateuszlewko** [JanMa/nomad-driver-nspawn#17]
It seems that restarting Nomad service (for example when upgrading Nomad or reloading configuration) restarts jobs run by nspawn driver. Docker jobs stay alive and are not restarted when restarting Nomad.

I observed the following errors in logs:
>   2020-10-26T19:28:26.592+0100 [ERROR] client.alloc_runner.task_runner: error recovering task; cleaning up: alloc_id=2fb194a7-5964-07f6-e9da-b3c09abfb3a5 task=<my nspawn task> error="rpc error: code = Unknown desc = failed to decode driver config: EOF" task_id=2fb194a7-5964-07f6-e9da-b3c09abfb3a5/<my nspawn task>/0af76d99
    2020-10-26T19:28:26.592+0100 [WARN]  client.alloc_runner.task_runner: error destroying unrecoverable task: alloc_id=2fb194a7-5964-07f6-e9da-b3c09abfb3a5 task=<my nspawn task> error="rpc error: code = Unknown desc = task not found for given id" task_id=2fb194a7-5964-07f6-e9da-b3c09abfb3a5/<my nspawn task>/0af76d99

Failed jobs are then reallocated and run fine, however, it's undesirable that they are restarted. 
Would it be hard to support that?

**Comment by JanMa** [comment]
Hello @mateuszlewko ,
normally it should be fine to restart Nomad and tasks started via this driver should also keep running.
I suspect you are running into an issue which I fixed in 9a578ffeeb548759bb7630d06cd21149de6f8252. Can you please update the driver to the latest release `0.4.0` and check if it is still not working?

If not, this is definitely a bug and I'll fix it!
Kind regards,
Jan

**Comment by JanMa** [comment]
I double-checked it and it seems the issue is also present in the latest version. I will make sure to fix this :+1:

**Comment by JanMa** [comment]
@mateuszlewko I just published a new release [0.4.1](https://github.com/JanMa/nomad-driver-nspawn/releases/tag/v0.4.1) which contains a fix for this issue

**Comment by mateuszlewko** [comment]
Confirmed that it's working now. Thank you!
