### ISSUE TITLE
"read_only and user_namespacing may not be combined" - is that really true?

### ISSUE THREAD

**Issue by xkxx** [JanMa/nomad-driver-nspawn#26]
Hello there,

Thanks for creating this nspawn driver for nomad! I've been playing around with it this weekend :)

I tried to enable `read_only` / `volatile` in a container and it refused to start, due to this validation rule: https://github.com/JanMa/nomad-driver-nspawn/blob/0217d363ac1c9d24950d37709dadf84a8fd38689/nspawn/nspawn.go#L224

I've looked online and couldn't find any info about this, so I'm curious about your experience with these flags interacting with `-U`. I've not tried `volatile` because of a lack of suitable containers, but running `systemd-nspawn` directly with `-U --read-only` seems to work fine. Has there been a recently change in systemd that made this combination work?

Thanks,

xkxx

**Comment by xkxx** [comment]
I did some more exploration and I think you are right.

With `--read-only` and `--private-users-ownership=chown`, `systemd-nspawn` fails with the error message you spoke of.
With `-read-only` and `--private-users-ownership=map`, `systemd-nspawn` doesn't complain.
With `--read-ony` and `--private-users-ownership=auto`, the result is like above.

So I can conclude that `--readonly` and `--volatile` are only a problem if `--private-users-ownership=chown`.

In the interest of allowing more powerful setups, I would advocate for allowing this :) These options are also a bit superfluous since most users would want user namespacing.

But I can also see the perspective of allowing the maximum compatibility of devices. If that's what you are going for, could we also expose a flag for `--private-users=pick --private-users-ownership=auto` that doesn't conflict with `--readonly`?

**Comment by JanMa** [comment]
I think the most convenient way for most users would be if the driver could check at runtime which ownership mode is chosen by `systemd-nspawn` and only throw the validation error if it's set to `chown`. But I also agree with you that exposing the raw `private-users` and `private-users-ownership` mode for more advanced use-cases might make sense. :+1:

**Comment by JanMa** [comment]
I just committed https://github.com/JanMa/nomad-driver-nspawn/commit/a7b857f7f92929b136f09bba4aa8264c9e296bf3 to `devel` which gives you some more fine-grained control about how user namespacing is enabled in a container. I will make a new release in the next days which will include this commit. The automated checking of which ownership mode is chosen by `systemd-nspawn` turned out to be way to complicated :grin:
