### ISSUE TITLE
Implement  https://github.com/arianvp/nomad-driver-systemd behaviour into this project?

### ISSUE THREAD

**Issue by arianvp** [JanMa/nomad-driver-nspawn#6]
Hey! Just found your project! Cool!

I've been working on something related https://github.com/arianvp/nomad-driver-systemd (though it's a bit abandoned and i was planning to work on it again). Namely scheduling systemd units using nomad.  Systemd units have all the same isolation primitives as systemd-nspawn containers;  and there is also https://systemd.io/PORTABLE_SERVICES/ which is a new feature in systemd for container-like workloads.

I was wondering; would you accept a PR for supporting running regular systemd services and portable services into this project? I think the projects are similar enough that fragmentation doesn't make sense here.

**Comment by JanMa** [comment]
Hey @arianvp,

thanks a lot for your interest in my project and for opening a bunch of issues
and PRs. You found a lot of the things which are already on my "I need to fix
this" list and I'll make sure to address them :-).

Regarding your proposal to merge the behavior of your
[nomad-driver-systemd](https://github.com/arianvp/nomad-driver-systemd) project into this one: 
I don't think it would be a good fit. My idea for this project is to create a
driver dedicated to run systemd-nspawn containers which at some point will
hopefully support (almost) all the features the docker, lxc and rkt drivers do.
Adding support for running arbitrary systemd units and also managing portable
services might be related to some extend to what this driver does but is not
really where I want to go with this project.


I think your approach of writing a dedicated driver for this use case might be
the better way to go.

Kind regards,
Jan

**Comment by arianvp** [comment]
Sounds good to me
